t=()
print(type(t))
t=(1,2,3,4,5,6,7,8,9)
print(t.count(1))
print(t.index(1))
print(tuple([2,3,4]))
print(t[::-1])
print(t+(1,2))
print(t*2)
print(1 in t)
print(len(t))
print(min(t))
print(max(t))
print(sum(t))
print(sorted(t,reverse=-1))
print(any(t))
print(all(t))
a, *b,c=(1,2,3,4)
print(type(b))# it will creates list of continous nums which are not assigned to other
a=1,2,3,4
print(a)
t = (1, [2, 3])
t[1].append(4)#mutables inside tuple can be changed
print(t)   # (1, [2, 3, 4])
